### PR TITLE
Reorganize source files for Swift Package Manager

### PR DESCRIPTION
**Pull request by briancroom**
This is the first piece of #226 extracted into a more manageable chunk.

It places the source files under a `Sources` directory where swiftpm expects them. Also adds `Package.swift`.

### CODE REVIEW

**Comment by modocache** [comment]
Looks good to me! But I'll defer to @jeffh. :bow:

**Comment by briancroom** [comment]
I've just realized that the podspec needs updates as a part of this. 

And Quick's is currently broken due to https://github.com/Quick/Quick/pull/436 😳

**Comment by modocache** [comment]
Oomph, yet another reason we need something like https://github.com/Quick/Quick/issues/238. Thanks for noticing!

**Comment by briancroom** [comment]
Added a podspec update now.

**Comment by jeffh** [comment]
Merged. Thanks @briancroom

**Comment by briancroom** [comment]
Thanks! I'll be opening some follow-ups shortly.

**Pull request merged**
