### PR TITLE
tvOS Support

### PR DESCRIPTION
**Pull request by brentleyjones**

### CODE REVIEW

**Comment by brentleyjones** [comment]
nimble-tvos-passing

**Comment by jeffh** [comment]
Thanks @brentleyjones!

**Comment by nickygerritsen** [comment]
@brentleyjones: this seems to have broken Carthage builds completely. Carthage does not expect more than two supported platforms per target.
Other projects just create a new scheme for tvOS instead of reusing the iOS version.
Is there a reason you did not do that here or is it better that we try to convince the Carthage guys that they support more platforms per target?

**Comment by brentleyjones** [comment]
It does support more than 2 platforms per target, as of 0.8.0. The called it "universal framework support".

**Comment by brentleyjones** [comment]
0.9: https://github.com/Carthage/Carthage/releases/tag/0.9
https://github.com/Carthage/Carthage/pull/622

**Comment by nickygerritsen** [comment]
Hmmm I swear I tested with 0.9.1. Will check it out later today

**Comment by nickygerritsen** [comment]
@brentleyjones: so if I have a `Cartfile` containing:
```ruby
github "Quick/Nimble" "master"
```

And my Carthage version:
```bash
$ carthage version
0.9.1
```

Then when I run
```bash
$ carthage update --platform ios
```

I get:
```bash
carthage update --platform ios                   
*** Fetching Nimble
*** Checking out Nimble at "70b901e55bad427d211b93586a83e0e3bca32034"
*** xcodebuild output can be found in /var/folders/ml/m9ry2pvd58j86jy3v6pycmfw0000gn/T/carthage-xcodebuild.3pTME0.log
*** Building scheme "Nimble-iOS" in Nimble.xcodeproj
fatal error: SDK count 4 in scheme Nimble-iOS is not supported: file /Users/mdiep/Repositories/Carthage/Carthage/Source/CarthageKit/Xcode.swift, line 959

Caught signal triggered by the Swift runtime!
Illegal instruction: 4

(etc.)
```

The same when I use `--platform tvos`. For you it does work? Because then I wonder what I'm doing wrong :(

**Comment by nickygerritsen** [comment]
OK this seems to be fixed in [0.9.2](https://github.com/Carthage/Carthage/tree/0.9.2), so I'll try this again soon :)

**Comment by brentleyjones** [comment]
Glad to hear. I was pretty sure it worked once.

**Pull request merged**
