### PR TITLE
Add BeEmpty() support to NSIndexSet

### PR DESCRIPTION
**Pull request by humblehacker**
`NSIndexSet` conforms to `NMBCollection`, so this is made explicit.

### CODE REVIEW

**Comment by briancroom** [comment]
Nice! Could you add an assertion to the unit tests that uses the `beEmpty` matcher with an `NSIndexSet` instance? That will help ensure that this conformance doesn't get inadvertently lost in the future. With that, if you could squash the commits I would be happy to merge this!

**Comment by humblehacker** [comment]
Thanks for your feedback @briancroom.  I've added tests for `beEmpty` and `haveCount` for `NSIndexSet`. In the process, I also made the following changes:

- Added a `testDescription` method to `NSIndexSet` to get its displayed string down to something reasonable. 
- Added a test for `NSIndexSet` stringification.
- Added missing calls to `stringify()` in the `HaveCount` matcher.
- Added some missing `NSSet` test cases to `BeEmptyTest.testBeEmptyNegative()`

**Comment by jeffh** [comment]
Hey @humblehacker:

Travis CI is reporting a build failure on Linux-Swift:

```
/home/travis/build/Quick/Nimble/Tests/Nimble/Matchers/BeEmptyTest.swift:65:34: error: argument type 'Int' does not conform to expected type 'AnyObject'
            expect(NSSet(object: 1)).to(beEmpty());
```

Swift Linux doesn't have automatic type coercion from `Int` to `NSNumber`, I think you'll just need to change that for the build to pass.

**Comment by humblehacker** [comment]
@jeffh Thanks for the feedback.  All tests green!

**Comment by briancroom** [comment]
LGTM! Thanks for the PR @humblehacker and sorry for the delay getting back to this.

**Pull request merged**
