### PR TITLE
Compile under Xcode 8 beta 1

### PR DESCRIPTION
**Pull request by sharplet**
Sets "Use Legacy Swift Language Version" to YES, i.e., `SWIFT_VERSION = 2.3`.

This change alone causes the following linker error:

    duplicate symbol __non_lazy_classes in:
        /Applications/Xcode-beta.app/Contents/Developer/Toolchains/Swift_2.3.xctoolchain/usr/lib/arc/libarclite_macosx.a(arclite.o)
        /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_macosx.a(arclite.o)
    duplicate symbol _OBJC_METACLASS_$___ARCLite__ in:
        /Applications/Xcode-beta.app/Contents/Developer/Toolchains/Swift_2.3.xctoolchain/usr/lib/arc/libarclite_macosx.a(arclite.o)
        /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_macosx.a(arclite.o)
    ld: 2 duplicate symbols for architecture x86_64

This appears to be caused by the "Implicitly Link Objective-C Runtime Support" build setting (a.k.a. `CLANG_LINK_OBJC_RUNTIME`). Disabling just this setting doesn't resolve the error, but disabling the
project-level ARC setting does resolve the linker error. As a result the `-fobjc-arc` compiler flag has to be set on each Objective-C file to ensure it is compiled with ARC enabled.

### CODE REVIEW

**Comment by sharplet** [comment]
It seems likely that this is just a bug in the beta's handling of Swift 2.3, so I'll probably file a radar.

**Comment by sharplet** [comment]
Radar: https://openradar.appspot.com/radar?id=5006639585296384

**Comment by NachoSoto** [comment]
Awesome, thanks for getting this started! Let me know if I can do anything to help.

**Comment by sharplet** [comment]
I just realised there's a problem with the tvOS target under Xcode 8. When I compile for tvOS, I get this warning:

```
warning: target specifies SWIFT_VERSION = '2.3', but it is overridden by TOOLCHAINS = 'com.apple.dt.toolchain.AppleTVOS10_0'
```

I haven't been able to work out a way to disable this, looks like it could be a bug specific to the tvOS 10 SDK.

**Comment by sharplet** [comment]
@jckarter and @ddunbar on Twitter have suggested some alternative workarounds:

- https://twitter.com/jckarter/status/742843265557221376
- https://twitter.com/daniel_dunbar/status/742893453038620672

Raising the deployment targets to latest resolves the issue for iOS and macOS. I can't really verify with tvOS at this point. However it's not really a change that's appropriate to push onto users, so I'm not sure we can move ahead with it.

I also tried disabling linking with standard libraries (i.e., `-nostdlib`), but that introduces other linker problems I'm not really sure how to resolve 😅

**Comment by ikesyo** [comment]
@sharplet https://github.com/Quick/Nimble/pull/302#issuecomment-226375515

It seems that #304 should fix the issue.

**Comment by sharplet** [comment]
Thanks @ikesyo tvOS is working now!

**Comment by sharplet** [comment]
Alright, CI is looking good on Xcode 7.3 on all platforms. I've just pushed another commit that adds Xcode 8 to the CI matrix.

**Comment by sharplet** [comment]
@Quick/contributors what are your thoughts about the idea of tagging v4.0.2 to include these changes?

**Comment by modocache** [comment]
Sounds great!! Thanks for the speedy work, @sharplet and @ikesyo!

**Comment by sharplet** [comment]
Ugh, both CI failures seem to be related to code signing for iOS under Xcode 8.

**Comment by sharplet** [comment]
I haven't been able to reproduce the failure locally. Not sure why it fails on Xcode 8 but not Xcode 7.3.

**Comment by ikesyo** [comment]
What happens if we apply the patch, removing `appletvos` and `appletvsimulator` from `SUPPORTED_PLATFORMS` on Nimble-iOSTests:

```diff
diff --git a/Nimble.xcodeproj/project.pbxproj b/Nimble.xcodeproj/project.pbxproj
index 1f929f9..099d0cb 100644
--- a/Nimble.xcodeproj/project.pbxproj
+++ b/Nimble.xcodeproj/project.pbxproj
@@ -1595,7 +1595,6 @@
 				METAL_ENABLE_DEBUG_INFO = YES;
 				PRODUCT_BUNDLE_IDENTIFIER = "net.jeffhui.${PRODUCT_NAME:rfc1034identifier}";
 				PRODUCT_NAME = NimbleTests;
-				SUPPORTED_PLATFORMS = "iphonesimulator iphoneos appletvsimulator appletvos";
 				SWIFT_OPTIMIZATION_LEVEL = "-Onone";
 			};
 			name = Debug;
@@ -1613,7 +1612,6 @@
 				METAL_ENABLE_DEBUG_INFO = NO;
 				PRODUCT_BUNDLE_IDENTIFIER = "net.jeffhui.${PRODUCT_NAME:rfc1034identifier}";
 				PRODUCT_NAME = NimbleTests;
-				SUPPORTED_PLATFORMS = "iphonesimulator iphoneos appletvsimulator appletvos";
 			};
 			name = Release;
 		};
```

**Comment by sharplet** [comment]
:fingers_crossed:

**Comment by ikesyo** [comment]
:weary:

> 2016-06-16 05:15:05.277 xcodebuild[1272:3682] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Canceling tests due to timeout in Checking test manager availability... If you believe this error represents a bug, please attach the log file at /Users/travis/Library/Developer/Xcode/DerivedData/Nimble-cynnqpiijwxeiicemrswimekklda/Logs/Test/83D7476C-50D3-4831-B4EC-4673EEC57661/Session-NimbleTests-2016-06-16_051302-HzlhfC.log" UserInfo={NSLocalizedDescription=Canceling tests due to timeout in Checking test manager availability... If you believe this error represents a bug, please attach the log file at /Users/travis/Library/Developer/Xcode/DerivedData/Nimble-cynnqpiijwxeiicemrswimekklda/Logs/Test/83D7476C-50D3-4831-B4EC-4673EEC57661/Session-NimbleTests-2016-06-16_051302-HzlhfC.log}
> 2016-06-16 05:15:05.316 xcodebuild[1272:6197] Connection peer refused channel request for "dtxproxy:XCTestManager_IDEInterface:XCTestManager_DaemonConnectionInterface"; channel canceled <DTXChannel: 0x7f9649aa3c00>

**Comment by sharplet** [comment]
Ok, so everything is fine on CI for all platforms except iOS on Xcode 8. Everything is peachy on my machine. @Quick/contributors what do you say we go ahead and merge this then push a new release?

**Comment by modocache** [comment]
Let's do it! 🚀






On Sat, Jun 18, 2016 at 4:14 PM -0400, "Adam Sharp" <notifications@github.com> wrote:












Ok, so everything is fine on CI for all platforms except iOS on Xcode 8. Everything is peachy on my machine. @Quick/contributors what do you say we go ahead and merge this then push a new release?

**Comment by briancroom** [comment]
Awesome!

**Comment by NachoSoto** [comment]
👏🏻

**Comment by sharplet** [comment]
After checking the [changes since v4.0.1](https://github.com/Quick/Nimble/compare/v4.0.1...master), I think it would be best to bump to v4.1.0. Working on the release notes now!

**Pull request merged**
