### PR TITLE
Opening up a PR to fix XCode 7.1 issues

### PR DESCRIPTION
**Pull request by leepfrog**
see work done from walkingsmarts/Nimble

### CODE REVIEW

**Comment by rpowelll** [comment]
It seems like we should probably add a target to build for tvOS, though I'm not sure if that needs to be done as part of this PR.

**Comment by jeffh** [comment]
Please make it as a separate PR. Thanks!

**Comment by jeffh** [comment]
Hey @leepfrog, does removing tvOS resolve any issues? I'll be look into it after I get Quick & Nimble to compile on xcode7.1

**Comment by jeffh** [comment]
Verified issues with tvOS. Thanks @leepfrog!

**Comment by leepfrog** [comment]
No problem!  Sorry, didn't see this til just now!

**Pull request merged**
