### PR TITLE
use private notification center during tests to prevent side effects

### PR DESCRIPTION
**Pull request by bgerstle**
Should make them less flakey.

### CODE REVIEW

**Comment by jeffh** [comment]
This change broke the Linux build :(

**Comment by bgerstle** [comment]
@jeffh the log isn't very helpful, any idea what could be wrong? should notification-based testing be run on OSX only, since it's specific to Foundation?

**Comment by jeffh** [comment]
Foundation Linux has NSNotificationCenter. The logs seemed to indicate
calling super wasn't allowed though.

**Comment by bgerstle** [comment]
@jeffh i found the offending build log statement, was just lost in all the Swift 3 warning noise.

**Comment by bgerstle** [comment]
it _seems_ like `setUp` is still called, even though Linux XCTest doesn't seem to have a `super` implementation :confused:

**Comment by briancroom** [comment]
@bgerstle yes that's correct, although the conditional won't be needed for too much longer. See: https://github.com/apple/swift-corelibs-xctest/pull/40

**Comment by bgerstle** [comment]
Nice!

**Comment by jeffh** [comment]
Merged. Thanks @bgerstle!

**Pull request merged**
