### PR TITLE
Order-indifferent sequence element matcher - containObjectSatisfying

### PR DESCRIPTION
**Pull request by jwfriese**
I'd like to share a matcher that I'd created on a couple private projects and found very useful.

Suppose I am designing a function that is returning some collection of complex objects, and the order of the objects does not matter: 

```swift
struct Turtle {
    var type: String!
}
var turtles = functionReturningSomeOrderIndifferentTurtles()
```

There are ways to test this already, but it seems that they would require me to write production code that I might not want to:
1) You could use Nimble's existing `contain` matcher, but that would require the collection's objects to conform to `Equatable`, which may not be necessary to the functioning of the production code. 
2) You could make the function return a strict ordering just for the purposes of test, but you shouldn't have to introduce that complexity to your production code just for the sake of making it testable in this way. I believe that writing code to be testable should be a goal of any developer, but the ordering of a truly order-indifferent API does not seem to be an appropriate application of that rule.  

I found in my own experience here that I wanted some type of matcher that allows testing of collection content without regard to ordering. It proved useful enough to share with the group in this PR. Please let me know if you feel like this would be a good addition to our set of matchers, and any feedback about the implementation itself. 

By the way, if you'd like to see it used in a real-world example, check out the following tests: 
https://github.com/jwfriese/Fleet/blob/master/FleetTests/CoreExtensions/Storyboard/StoryboardDeserializerSpec.swift

### CODE REVIEW

**Comment by jeffh** [comment]
Hey @jwfriese,

I think that's a great idea. I've left comments inline for the actual PR. Other than my comments, it all looks good to me 👍

**Comment by jeffh** [comment]
Also, don't forget to add documentation in the README.

**Comment by jwfriese** [comment]
@jeffh - Too much time must have passed since I last had my code reviewed... I seem to have forgotten how to see your comments, Jeff 😅 Where do I look to find the changes you've suggested?

**Comment by jeffh** [comment]
@jwfriese, my bad – I forgot to submit the review. I always do this 😞

**Comment by jwfriese** [comment]
@jeffh - No worries at all, it's happened to me before. 

I've addressed all your comments, and also slipped in a rename from `ContainObjectSatisfying` to `ContainElementSatisfying`, which I think is a more appropriate name. 

Let me know if there are any other changes you'd like to see, and thanks for being quick with your feedback.

**Comment by jeffh** [comment]
LGTM, thanks @jwfriese!

**Pull request merged**
