### PR TITLE
Swift 2.0 support

### PR DESCRIPTION
**Pull request by keith**
Closes https://github.com/Quick/Nimble/issues/184

### CODE REVIEW

**Comment by modocache** [comment]
Any thoughts, @jeffh? :raised_hands:

**Comment by jeffh** [comment]
Merged, thanks @keith.

Sorry, I was busy upgrading my devices to GM :hourglass:

**Comment by keith** [comment]
No problem! Thanks!

**Comment by modocache** [comment]
@jeffh Mind if I delete the `swift-2.0` and `swift-1.1` branches? I did so on https://github.com/Quick/Quick to prevent confusion when submitting pull requests--which I think may have happened on #192 and #193.

**Comment by modocache** [comment]
Ended up deleting the branches. Pretty sure you can restore them if necessary anyway.

**Comment by jeffh** [comment]
👍 agreed! Thanks for going ahead and doing it.

**Pull request merged**
