### PR TITLE
Adds podspec linting to CI

### LINKED ISSUE #285: Add `pod lib lint` to CI
As discussed in #284, the Nimble pod should be linted regularly to ensure that releases can be pushed to CocoaPods Trunk. This step should be part of the regular CI process to catch any issues early.

### PR DESCRIPTION
**Pull request by ashfurrow**
This is just one approach, we could add podspec linting to an existing build process instead (either of OS X or iOS).

Continued from #286.
Fixes #285.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Strange that it failed only on merge. Could be a Travis thing involving changes to its config file? I'm willing to bet if we merged it, master would be fine, and if it does fail, we could revert. Open to suggestions.

**Comment by phatblat** [comment]
I'm game. Let's see how it goes.

**Comment by phatblat** [comment]
Well, the podspec build worked fine but one [test failed](https://travis-ci.org/Quick/Nimble/builds/125457370) in an unrelated build ¯\_(ツ)_/¯

**Comment by ashfurrow** [comment]
Can't win them all 😄

**Comment by briancroom** [comment]
Strange, I don't remember having seen that test be flaky before. Anyway I restarted the job and it passed, so :tada: 

Thanks @ashfurrow!

**Pull request merged**
