### PR TITLE
[BREAKING] Migrate to Swift 4.1 and drop Swift 3.x support

### PR DESCRIPTION
**Pull request by ikesyo**
Ref: #514

### CODE REVIEW

**Comment by ikesyo** [comment]
https://travis-ci.org/Quick/Nimble/jobs/364948714

<pre>
 -> Nimble (7.1.0)
    - ERROR | swift: Specification `Nimble` specifies an inconsistent `swift_version` (`4.0`) compared to the one present in your `.swift-version` file (`4.1`). Please remove the `.swift-version` file which is now deprecated and only use the `swift_version` attribute within your podspec.
</pre>

This is annoying... `.swift-version` is for [swiftenv](https://github.com/kylef/swiftenv), not for CocoaPods. 😕

**Comment by ikesyo** [comment]
@Quick/core Please review 🙏

**Comment by ashfurrow** [comment]
Looks good to me 👍

**Comment by wongzigii** [comment]
🚢 Let's get rid of the (swift>= 4.0) version check.

**Comment by ikesyo** [comment]
Thanks all! 🎉

**Pull request merged**
