### PR TITLE
Xcode 10 support

### PR DESCRIPTION
**Pull request by sharplet**
The error fix is non-breaking, but less certain about the IUO warnings.

### CODE REVIEW

**Comment by Buju77** [comment]
I'm currently also having a endless recursion crash in `stringify()` method:
  
screen shot 2018-06-05 at 13 35 37

my invoking code looks like this:

```
var user: RTDatabaseUser!

...

expect(self.user).toNot(beNil(), description: "register should never fail!")
```

any idea how i could fix this?

**Comment by Dschee** [comment]
@Buju77 I just came across the same issue and reported it on Quick [here](https://github.com/Quick/Quick/issues/796). Looks like it's part of Nimble. Let me have a look and try to fix this real quick ...

**Comment by Dschee** [comment]
I fixed this particular issue, though now I'm running into a different one. Looks like Xcode 10 support needs some more work, let me continue fixing stuff ...

**Comment by Dschee** [comment]
Okay, the second issue I've found was an issue with Nimbles internal tests. When building Nimble via Carthage in a project and using it for tests, everything is working now as expected, so I fixed the above issue and sent a Pull Request onto the branch of this PR [here](https://github.com/Quick/Nimble/pull/532).

@sharplet Would you mind have a look and merge, please?

**Comment by Buju77** [comment]
@Dschee cool thx. My tests are now working again. 👍

**Comment by sharplet** [comment]
Discussing details of @Dschee's `stringify` fix over here: https://github.com/Quick/Nimble/pull/532#issuecomment-394761113.

**Comment by sunshinejr** [comment]
With the fix of #532 it works on my end as well, good job guys 👍

**Comment by sharplet** [comment]
It would be nice to also have this on CI, but that will probably take a little while. Shouldn't stop us from merging this I would hope. @Quick/core where do we stand on the definition of breaking changes? This _should_ be a source-compatible change, in which case it seems fine to include this in a patch release. Not binary compatible though.

**Comment by ikesyo** [comment]
I'm fine for releasing this in a patch release. 👍

**Comment by ikesyo** [comment]
I've ran the test suites on this branch but it failed 😱

**Comment by sharplet** [comment]
Is anyone at WWDC that could take this crash to the a Swift lab?

In any case, I'm going to go ahead and merge!

**Comment by phatblat** [comment]
🙋🏻‍♂️I’m at WWDC and spending most of my time in the labs. I’ll take this to the swift lab today

**Comment by sharplet** [comment]
@ikesyo Interested in tagging 7.1.2?

**Comment by ikesyo** [comment]
I went to the Swift Open Hours lab and @jckarter answered that this may be a Swift compiler bug.

**Comment by ikesyo** [comment]
@sharplet Okay, I will backport this to 7.x branch and release 7.1.2.

**Comment by phatblat** [comment]
Lol I just got the same answer in the labs. @ikesyo did you file a radar I can dupe?

**Comment by ikesyo** [comment]
@phatblat No rader yet

**Comment by phatblat** [comment]
Radar: [40857699](https://openradar.appspot.com/radar?id=5595735974215680) "Swift runtime crash when closure passed as @noescape is mistakenly identified as having escaped (Nimble)"

**Pull request merged**
