### PR TITLE
Add be present matcher

### PR DESCRIPTION
**Pull request by mothule**
The PR should summarize what was changed and why. Here are some questions to
help you if you're not sure:

- What behavior was changed?
  - Add bePresent() matcher method.
- What code was refactored / updated to support this change?
  - Nothing in particular.
- What issues are related to this PR? Or why was this change introduced?

I writes as follows now.
```swift
expect(actual).toNot(beNil())
```

I don't want to use `toNot`, I don't think it's intuitive.
I want to write as follows.
```swift
expect(actual).to(bePresent())
```

Checklist - While not every PR needs it, new features should consider this list:

- [x] Does this have tests?
- [x] Does this have documentation?
- [ ] Does this break the public API (Requires major version bump)?
- [x] Is this a new feature (Requires minor version bump)?

Thank you for your consideration. 😄

### CODE REVIEW

**Comment by ikesyo** [comment]
Thanks for the pull request! However, I'm not sure if this matcher is existed or popular in other matcher frameworks (not only at Cocoa development but at other languages). It would be great if you could provide convincing information.

**Comment by mothule** [comment]
@ikesyo 
Thank you reply! 😁

I often use RSpec as a testing framework for Rails applications.
RSpec can call the instance method of the `actual` class using the[`be` method](https://github.com/rspec/rspec-expectations/blob/a7205975dcda3f53466ba5952f7dec8ac452e18c/lib/rspec/matchers.rb#L349-L351).

An example

```ruby
expect(actual).to be_empty
expect(actual).to be_present
# ↑ The `empty?` And `present?` Methods are defined in the instance method of the `actual` class.
```


I'm using `be_present` in RSpec. 😄

## About popularity

It's difficult for me to judge.
Searching on GitHub found 66,855 files.
Is this unpopular?
https://github.com/search?l=Ruby&q=be_present&type=Code

## About name
If the name is incorrect, I can change it to another name.
Because I often use `beNil()`. But `toNot(beNil())` is just HARD TO READ.

Thank you for your consideration. 😄

**Comment by ikesyo** [comment]
Thanks for the input!

I've now understood that the `be_present` consists of RSpec's `be` matcher and [`present?` method](https://api.rubyonrails.org/classes/Object.html#method-i-present-3F) (defined by ActiveSupport). `present?` is the inverse of [`blank?`](https://api.rubyonrails.org/classes/Object.html#method-i-blank-3F). `blnak?`'s description is:

> An object is blank if it's false, empty, or a whitespace string. For example, nil, '', ' ', [], {}, and false are all blank.

so `blank?` and `present?` is not just nil/non-nil check. That is something like `beTruthy`/`beFalsy` concept (e.g. https://jestjs.io/docs/en/expect#tobetruthy). Even though Nimble itself has `beTruthy`/`beFalsy` matchers, because Swift doesn't offer implicit Bool conversion from arbitrary types, the matchers only accept Bool-like types unfortunately.

I think the `bePresent` is heavily based on Ruby/RSpec/Rails contexts. I assume that is not appropriate for the exact inverse of `beNil` and the name does not fit well to Objective-C/Swift/Cocoa Programming contexts.

About popularity, I didn't mean popularity of the matcher usages in Ruby/Rails users, but meant **popularity of the matcher definition in various matcher frameworks** (e.g. KiWi/Expecta/OCHamcrest for Cocoa, Jasmine/Mocha/Jest for JavaScript, and so on). As described above, I think `be_present`/`bePresent` is actually specific for Ruby/Rails.

More simpler and correct name will be `beNonNil`, but

- `expect(someNillable).to(beNonNil())` and `expect(someNillable).toNot(beNil())` are not so diffrent
- `expect(someNillable).toNot(beNonNil())` seems confusing (double negation)

As a consequence, I'm not still convinced that adding the matcher to Nimble is worth adding.

**Comment by mothule** [comment]
Thank you for your kind reply.

The popularity was the adoption rate of the test framework.
This is my feeling, but `be_present` is not used in other test frameworks ...

As you pointed out, `present` represents not only nil but also` empty`.
It would be nice if there was a antonym for nil ... 😢

I understand the conclusion.
I will close this PR.

**Pull request closed without merging**
