### PR TITLE
Xcode 8 beta 2

### PR DESCRIPTION
**Pull request by ikesyo**
- Remove the workaround for linker error on Xcode 8 beta 1: https://github.com/Quick/Nimble/pull/302#issue-160088167
- Add missing tests for Nimble-tvOSTests target
- Disable code signing for device builds on Xcode 8

### CODE REVIEW

**Comment by sharplet** [comment]
It look like the CI failures are because [Travis CI hasn't updated to beta 2 yet](https://docs.travis-ci.com/user/osx-ci-environment/#Xcode-8)?

**Comment by ikesyo** [comment]
Yes, they does not announce anything about beta 2 support yet.

**Comment by sharplet** [comment]
Tests pass on my machine. lgtm 👍

**Comment by sharplet** [comment]
Tested on both Xcode 7.3 and Xcode 8 beta 2

**Comment by sharplet** [comment]
Carthage builds all succeed too! 👏

**Pull request merged**
