### PR TITLE
[WIP] Adds podspec linting to CI

### LINKED ISSUE #285: Add `pod lib lint` to CI
As discussed in #284, the Nimble pod should be linted regularly to ensure that releases can be pushed to CocoaPods Trunk. This step should be part of the regular CI process to catch any issues early.

### PR DESCRIPTION
**Pull request by ashfurrow**
This is just one approach, we could add podspec linting to an existing build process instead (either of OS X or iOS).

Fixes #285.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Well that didn't go as planned. 

screen shot 2016-04-22 at 10 15 50 pm

The error seems to be from Ruby itself, which is segfaulting. It shouldn't do that – even with invalid Ruby code the runtime shouldn't segfault, as far as I understand it. Going to ask some smarter people and see what they think.

**Comment by ashfurrow** [comment]
I wasn't able to reproduce this crash locally, but I'm running system Ruby and Travis is running RVM with a _slightly_ different version number. I saw [others](https://github.com/flori/json/issues/229) were having a similar issue with the json gem that appears to be causing the segfault, and a common solution is to change Ruby versions. I've tried specifying in the Travis config 2.2 instead of 2.0, we'll see.

**Comment by ashfurrow** [comment]
Moving this to a work-in-progress while I try some things with CI. 

Looking at this with fresh eyes, I see that originally it was the `json` gem segfaulting, but when I try to do a `gem install json`, it's `psych` that is segfaulting. This leads me to wonder if the problem is running Ruby in general, since otherwise we don't do it on CI. I think this is a possibility given the problems that Travis has had with running Ruby code on OS X machines (and we're using a "general" machine with `os: ox`, might be an edge case). Looking into it...

**Comment by phatblat** [comment]
IIRC, `psych` has given me headaches with different versions of Fastlane and uninstalling `psych` was the fix. Lately, I've been using bundler to install gems local to a project so that I don't have to do any cleanup like this.

**Comment by ashfurrow** [comment]
Agreed using Bundler is preferable to avoid problems like this :+1: It also makes using specific versions (and beta versions) of CocoaPods a breeze.

**Comment by ashfurrow** [comment]
Whoa, got it to work with `sudo`. Gonna try something less drastic.

**Comment by ashfurrow** [comment]
Hmm. I'm more and more suspicious that this is a problem on Travis' end caused by an edge case of `language: generic` and `os: osx`. In fact, Travis specifies this in their [documentation](https://docs.travis-ci.com/user/multi-os/#Operating-System-differences):

> Not all tools may be available on OS X.

I think it's not unlikely that this generic/osx combo wasn't tested to make sure gems like CocoaPods can run (since my `puts "hi"` test worked).

**Comment by ashfurrow** [comment]
This is working for the push check, but not the pr check. Not sure why. In any case, I'm moving this to another pull request that has these squashed (I want to leave the commits as a record in case they help someone else).

**Comment by ashfurrow** [comment]
Reopening to test something

**Comment by ashfurrow** [comment]
Ha, so updating to the latest-and-greatest `json` gem somehow causes `bundle install` to segfault on `psych`? Dunno how that works. Still playing around to see if I can get this without requiring `sudo`.

**Comment by ashfurrow** [comment]
Well, it wasn't meant to be.

**Comment by phatblat** [comment]
Wow, didn't expect that to be so difficult

**Comment by ashfurrow** [comment]
Agreed, surprised me too. Can you take a look at #288 when you have a moment? It follows your advice on using bundler.

**Pull request closed without merging**
