### PR TITLE
Operators and [Double] support for beCloseTo matching

### PR DESCRIPTION
**Pull request by feinstruktur**
In a nutshell:
```
expect(1.0) ~= 1.0001
expect(1.0) == (1.002, 0.005)
expect(1.0) == 0.9 ± 0.2
```
I've also added matching of Double arrays (identical delta for all elements):
```
expect([0.0, 1.0]) ~= [0.0001, 1.0001]                       // using the default delta of 0.0001
expect([0.0, 1.0]).to(beCloseTo([0.1, 1.1], within: 0.1))    // using the given delta of 0.1
```

### CODE REVIEW

**Comment by feinstruktur** [comment]
Yes, `~=` looks a lot like a regex matching operator. Quite conceivable that it will at some point clash with a regex library using it.

Originally I was thinking of using `≈` instead of `~=` but I dismissed it because I couldn't find a keyboard shortcut to type it. Short of knowing the unicode sequence or copy pasting it from somewhere there doesn't seem to be a simple way of actually typing it.

Otherwise it would be pretty ideal - it's the corresponding math symbol, it's unlikely to be overloaded for anything else and it's not commonly used as an operator at all yet.

Should we go for that? It would make code prettier to read albeit harder to write. Maybe there's an Xcode snippet I could add to create a shortcut or something.

**Comment by modocache** [comment]
Thanks for the pull request, @feinstruktur! :wave: :grin: 

RSpec dropped support for matcher operators like `==` when they migrated to the `expect(...).to(...)` syntax, primarily due to [runtime warnings from the Ruby interpreter](http://myronmars.to/n/dev-blog/2012/06/rspecs-new-expectation-syntax). Since we don't have that problem in Swift, I'm not opposed to matcher operators.

I'm largely ambivalent, though.

I don't think they provide enough value to justify the lines of code needed to define them--even if that's a very small amount. But I personally don't use them, so I really can't speak to how useful they are! :speak_no_evil: :banana: 

I would say that `~=` reminded me of the Ruby operator `=~`, so I think I'd find it confusing to use. But again, I don't normally use matcher operators, so take that with a grain of salt.

**Comment by jeffh** [comment]
Is option-x the hotkey you're looking for?

I'm not at a computer to try this out.

**Comment by modocache** [comment]
Option-x makes `≈` for me. That's pretty awesome, actually. :open_mouth:

**Comment by feinstruktur** [comment]
Ah cool - it doesn't on a UK keyboard but that's not a big deal really. US layout is probably by far the most commonly used. I'll be travelling the next couple of days but if everyone's happy with `≈` I'll make that change when I'm back.

**Comment by paulyoung** [comment]
It also looks like bacon ≈ :+1:

**Comment by modocache** [comment]
Can't unsee.

**Comment by feinstruktur** [comment]
Ok, the bacon operator is now available ;)

**Comment by jeffh** [comment]
Thanks @feinstruktur for the yummy bacon! :+1:

**Pull request merged**
