### PR TITLE
Added 'toSucceed' matcher

### PR DESCRIPTION
**Pull request by Rivukis**
The PR should summarize what was changed and why. Here are some questions to
help you if you're not sure:

 - What behavior was changed?
 - What code was refactored / updated to support this change?
 - What issues are related to this PR? Or why was this change introduced?

Checklist - While not every PR needs it, new features should consider this list:

 - [x] Does this have tests?
 - [x] Does this have documentation?
 - [ ] Does this break the public API (Requires major version bump)?
 - [x] Is this a new feature (Requires minor version bump)?

### CODE REVIEW

**Comment by Rivukis** [comment]
This allows users to make their own validations inside a closure.

I made this when I was 'TDD'ing a personal project that used a lot of enums with associated values. This made it so much easier write tests without having a lot of unnecessary conformances to Equatable.

No changes to the README.md file have been done for this matcher yet (not sure about the process for that)

**Comment by Rivukis** [comment]
This was even more helpful when combining with `toEventually`.

**Comment by jeffh** [comment]
Hey @Rivukis,

This looks great! I just have a question:

Did you consider passing the closure to `succeed` instead of the expectation? I'm curious on your thoughts about that as an alternative solution. I'm thinking something like:

```swift
expect(2).to(succeed({ actual in
    return actual.evaluate() == 2 ? .succeeded : .failed(reason: "some reason")
}))
```

It may be not as concise in your enum case, but it might be more generalized to handle more scenarios. (Of course if the closure was in the matcher the name of the matcher might need to change.)

**Comment by jeffh** [comment]
Also I forgot to talk about the documentation.

The documentation for Nimble is normally added to README. I'd probably put this one under 'Built-in Matcher Functions', right above 'Writing Your Own Matchers'.

**Comment by Rivukis** [comment]
@jeffh, I'm looking into your suggestions and I agree that would look and feel better. The problem is `expect()` requires a parameter, and I don't like putting in an arbitrary value to make it work.

Options I've come up with:
1. Keep this version.
2. Make a version of `expect()` that doesn't require a parameter.
3. Have the return value of the closure conform to `Equatable` and have the expected return value be the parameter in `expect()`

The issues with #3:
1. The user may only need a true false situation, so using true feels unnecessary.
2. Requires the return value to be an Equatable type instead of an enum where the necessary information is required by said enum
2. How does the user communicate a failure reason. I've built a working version that uses an inout parameter and throwing errors to communicate a failure reason. Neither feels great or obvious to the user.

My preference is #2 (version of `expect()` that doesn't take a parameter), but I wanted to get the opinion of those who know more about the internals of Nimble than I do. Any help is very much appreciated.

**Comment by Rivukis** [comment]
After thinking about it, I prefer Option 1. Anyway let me know what you all think, and what I can do to get this merged in. Thank you.

**Comment by jeffh** [comment]
Hey @Rivukis,

Thanks for responding. I just wanted to make sure that you considered other possibilities besides the current implementation. But this solution is probably the best option for a quick drop-in custom matcher.

Thanks @Rivukis! 🎉

**Pull request merged**
