### PR TITLE
Add 'haveCount' matcher

### PR DESCRIPTION
**Pull request by mkauppila**
In reference to #158, I deciced to implement `haveCount` matcher. I’d :heart: to get code review or other comments, especially if there’s something that still needs tweaking :grinning:

### CODE REVIEW

**Comment by jeffh** [comment]
Looks good @mkauppila :+1: I do think it would be nice to expand `haveCount` to the more general `SequenceType` or `CollectionType` in swift. Same for some of the Foundation Objective-C types: `NSDictionary`, `NSSet`, `NSHashTable`.

**Comment by jeffh** [comment]
Also, don't forget to document this matcher in the README :smile:

**Comment by mkauppila** [comment]
Thanks @jeffh. It would make sense to expand it to more general type. `count` seems to be defined in `CollectionType` and that's what we need here, so `CollectionType` it will be.

Oh, I totally forgot the documentation :grin: Thanks for pointing it out!

**Comment by mkauppila** [comment]
@jeffh I noticed that `NMBCollection` protocol is currently only extended to `NSSet`, `NSDictionary`, `NSHashTable` and `NSArray` (through `NMBOrderedCollection`). Wouldn't it make sense to also extend the aforementioned protocol to [NSMapTable](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/NSMapTable_class/)? I see no reason why not, because `NSMapTable` also implements `count`. If you agree, I can do the changes in another PR :smiley:

**Comment by mkauppila** [comment]
Even though CircleCI is once again showing red. All the changes discussed above are done. So all comments are welcomed :flags:

**Comment by jeffh** [comment]
Yeah. Add NSMapTable too. I forgot about that one. Thanks!

**Pull request merged**
