### PR TITLE
Update CwlPreconditionTesting

### LINKED ISSUE #471: Compiling fails in Xcode 9 / Swift 4 / Nimble 7.0.2
### What did you do?

Compile Nimble in Xcode 9 9A235

### What did you expect to happen?

It Compiles

### What actually happened instead?

It gives me the compilation error:

```
CwlPreconditionTesting/CwlPreconditionTesting/CwlCatchBadInstruction.swift:82:11: Overlapping accesses to 'self', but modification requires exclusive access; consider copying to a local variable
```

### Environment

List the software versions you're using:

 - Quick: *1.1.0*
 - Nimble: *7.0.2*
 - Xcode Version: *9.0 (9A235)*
 - Swift Version: *4.0*

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.3.1*

### Project that demonstrates the issue

https://github.com/Blackjacx/SHSearchBar

### PR DESCRIPTION
**Pull request by ikesyo**
Should fix #471.

- https://github.com/mattgallagher/CwlPreconditionTesting
- https://github.com/mattgallagher/CwlCatchException

### CODE REVIEW

**Comment by ikesyo** [comment]
@Blackjacx Could you try with this branch?

**Comment by Blackjacx** [comment]
Yep with this PR it works! Great 👍

**Comment by ikesyo** [comment]
@Quick/core Any thoughts?

**Comment by ashfurrow** [comment]
Hmm, pretty big diff. Would you mind giving a high-level description of what changed? Just curious what the issue was.

I trust your judgement, plus we've had @Blackjacx test, so I'm good to merge 👍

**Comment by ikesyo** [comment]
The first point is the commit which actually fixes #471: https://github.com/mattgallagher/CwlPreconditionTesting/commit/0e5ac0b417b61e6f7054a734eb7d53f1961b0b31

So updating CwlPreconditionTesting is required here.

The second point is that we now use Carthage (`Cartfile.private`) as a package manager to pull CwlPreconditionTesting (and CwlCatchException) sources into Nimble instaed of copying them manually, as discussed originally in https://github.com/Quick/Nimble/pull/248#issuecomment-189753786:

> > I made CwlPreconditionTesting a submodule, and then included the files from it statically. Is this the right way to go?
>
> Ideally some versioned dependency would be better, but CwlPreconditionTesting probably doesn't fit well with package managers. The submoduled project doesn't support Cocoapods or SPM.

I used Carthage because of the following reasons:

- CocoaPods can be used as well but that would produce unnecessary `Nimble.xcworkspace`
- SwiftPM handles dependencies as git repositoreis, so checking them in would be annoying
  - The standard tool might be preferable though

**Comment by ikesyo** [comment]
> Hmm, pretty big diff

If we explicitly depend on CwlPreconditionTesting and declare that on `Cartfile`, `Nimble.podspec` and `Package.swift` instead of embedding the dependency, the big diff can be avoided.

**Comment by ikesyo** [comment]
> Hmm, pretty big diff

How does this look like now?

**Pull request merged**
