### PR TITLE
Add support for watchOS

### PR DESCRIPTION
**Pull request by JosephDuffy**
This PR is to add support for running on watchOS. Since Xcode 12.5 watchOS has been supported but Nimble doesn't currently compile for watchOS.

A new target has been added to the project, along with explicit support in the Package.swift.

I don't believe anything here is a breaking change.

I have a [fork of Quick that also supports watchOS](https://github.com/JosephDuffy/Quick). I'll create a PR for that if this PR gets approved and merged.

### CODE REVIEW

**Comment by younata** [comment]
Hey @JosephDuffy, thank you for this! I'd love to get this in. I just merged main into it. Perhaps this should also include a revert of https://github.com/Quick/Nimble/pull/953 (or, at least, disable throwException if you run the test suite on actual hardware)? Sorry to add that extra work on you.

**Comment by younata** [comment]
In the interest of getting v10 released sooner, I'm going to move watchOS support to the next major release (v11).

**Comment by JosephDuffy** [comment]
@younata I've re-enabled watchOS support, I think this PR is ready again. Once this is merged I'll create the accompanying PR for Quick.

**Review by younata — CHANGES_REQUESTED** [review]
Thanks for updating this!

I think this overall looks good. A couple requests/suggestions though:

- Can this target watchOS 5.0 and later? we're planning on the next releases of Quick and Nimble to target the (as of this comment) last 4 major releases of iOS, macOS, and tvOS. Applying that same standard would mean targeting watchOS 5.0. (Just setting the version target to 5.0 doesn't seem to cause compilation issues, and the unit tests here still pass).
- Instead of setting the watchOS deployment target individually in the `Nimble-watchOS` and `Nimble-watchOSTests` targets, it would be easier to maintain if we set watchOS deployment target of the project, and let each target inherit the deployment target. (We're not currently doing that in Nimble, [this PR in Quick](https://github.com/Quick/Quick/pull/1146) is making that change to Quick, and I'll be making a PR to Nimble in the coming weeks to have OS deployment target versions set in the project and inherited by each target)
- Let's update the Nimble.podspec to also specify a watchOS deployment version (and also the excluded files).

Thank you so much! We really appreciate this.

**Comment by JosephDuffy** [comment]
I've made the requested changes, although it's worth noting that watchOS tests can't be run on watchOS versions older than 7.4.

This is enforced by Xcode, but I thought it would be a compilation error rather than an error when trying to run the tests, which is why I originally had this set to watchOS 7.4.

**Review by younata — APPROVED** [review]
> I've made the requested changes, although it's worth noting that watchOS tests can't be run on watchOS versions older than 7.4.
> This is enforced by Xcode, but I thought it would be a compilation error rather than an error when trying to run the tests, which is why I originally had this set to watchOS 7.4.

Huh. Odd.

Thanks for taking care of this! I think it's good to merge.

**Pull request merged**
