### PR TITLE
tvOS Support

### PR DESCRIPTION
**Pull request by jeffh**
Adds a new build target for tvOS

### CODE REVIEW

**Comment by neilpa** [comment]
This should explicitly set `ENABLE_BITCODE = YES` to be buildable from Carthage.

```
Build settings from command line:
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = appletvos9.0

=== BUILD TARGET Nimble-tvOS OF PROJECT Nimble WITH CONFIGURATION Release ===

Check dependencies
target 'Nimble-tvOS' has bitcode disabled (ENABLE_BITCODE = NO), but it is required for the 'appletvos' platform
```

**Comment by jeffh** [comment]
Hmm, historically XCTest doesn't contain bitcode which would cause the same issue as https://github.com/Quick/Quick/pull/409 and https://github.com/Quick/Nimble/issues/170.

I'll have to take a look more thoroughly when I get more time.

**Comment by jeffh** [comment]
Hey @neilpa, I've enabled bitcode for tvOS

**Comment by neilpa** [comment]
This now fails to link because of the issue you called out earlier.

```
ld: '/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE) or obtain an updated library from the vendor for architecture arm64
```

I'm not sure how to resolve these two competing problems.

**Comment by neilpa** [comment]
I checked out just Nimble to experiment. Xcode must be doing something special because that builds and runs tests fine. However, I see the exact same failures from the command line with `xcodebuild -target Nimble-tvOSTests`

**Comment by neilpa** [comment]
Specifying the scheme+destination instead of target seems to work regardless of bitcode setting. (c.f. http://www.mokacoding.com/blog/xcodebuild-destination-options/)

```
❯ xcodebuild -scheme Nimble-tvOS -destination 'platform=tvOS Simulator,name=Apple TV 1080p'
```

My guess for fixing this is remove `arm64` from supported platforms for now. Seems like you can't have a real device test target that also links other frameworks because of the xctest bitcode discrepancy.

**Comment by neilpa** [comment]
Specifying the sdk explicitly seems to work (which is what xcode must be doing)

```
❯ xcodebuild -target Nimble-tvOSTests -sdk appletvsimulator9.0
```

**Comment by jeffh** [comment]
@neilpa, Please submit a PR for this. My apple tv has not arrived yet (it got lost in shipping), so I can only verify the simulator.

**Comment by neilpa** [comment]
I don't have a tvOS, I was just messing around with xcodebuild to try and make it work by hand from the command line. I'm not sure what the necessary Xcode settings are because nothing I tried ended up working.

**Comment by NachoSoto** [comment]
Yeah I'm seeing this too:
```
ld: '/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE) or obtain an updated library from the vendor for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I think removing `arm64` makes sense: if `XCTest` does not contain `bitcode` at the moment, there is no way to run tests on an Apple TV.

**Comment by brentleyjones** [comment]
I'm also seeing it, with Xcode 7.2:

```console
ld: '/Applications/Xcode-7.2.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE) or obtain an updated library from the vendor for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Pull request merged**
