### PR TITLE
Better Xcode 8 support

### PR DESCRIPTION
**Pull request by ikesyo**
Supersedes #320.

### CODE REVIEW

**Comment by ikesyo** [comment]
ping

**Comment by ashfurrow** [comment]
Looks 👍 to me.

**Comment by ikesyo** [comment]
Is there any chance to get this merged? 😅

**Comment by ikesyo** [comment]
I'm willing to be a contributor if you contributors don't have much resources for the project for now. :pray:

**Comment by ikesyo** [comment]
ping (related to #325)

**Comment by modocache** [comment]
Oops, sorry @ikesyo! I just sent you a Twitter message about becoming a maintainer. I hadn't realized you'd already posted about it here. Sure thing, I'll add you!

**Comment by modocache** [comment]
> I'll add you!

Done! Thanks a lot for your help, sorry it took so long. And thanks, of course, for the pull request! ❤️

**Comment by ikesyo** [comment]
Thank you too @modocache!!

**Pull request merged**
