### PR TITLE
[7.x] Set `APPLICATION_EXTENSION_API_ONLY` to `YES`

### LINKED ISSUE #477: Swift 4 SWIFT_CLASS produces symbol duplication (Swift 4)
- Nimble: *7.0.2*
 - Xcode Version: *9.1 beta (9B37)*
 - Swift Version: *4*
 - Platform: *MacOS*

I am using cocoapods with next structure:
```
use_frameworks!

$rxSwiftVersion = '~> 4.0'
$resultVersion = '~> 3.0'

...

target :'MyKit-macOS' do
    platform :osx, '10.13'

    pod 'RxSwift', $rxSwiftVersion
    pod 'Result', $resultVersion
end

target :'MyKit-macOSTests' do
    platform :osx, '10.13'

    pod 'RxBlocking', $rxSwiftVersion
    pod 'RxTest', $rxSwiftVersion
    pod 'Nimble'
end
```

### What did you do?

build MyKit for testing. Nimble framework could not be built because of duplicated symbols occurring in DSL.m "SWIFT_CLASS("_TtC6Nimble7NMBWait") ..." and CurrentTestCaseTracker.h
"SWIFT_CLASS("_TtC6Nimble22CurrentTestCaseTracker")"

### What did you expect to happen?

I expect nimble to be built normally ;)

If I remove this SWIFT_CLASS declaration of interfaces in ObjC files - then it is building normally.
I expect that currently with Swift 4 Objective-C could get symbols marked with @objc without any issues, and therefore it is conflicting during compilation time with this particular declarations.

After removing SWIFT_CLASS declaration I tried unit tests for both ObjC and Swift:

```
@interface ObjCTest : XCTestCase

@end

@implementation ObjCTest
- (void)testExample {
    [NMBWait untilTimeout:3 file:@"" line:1 action:^(void (^ _Nonnull callback)(void)) {
        callback();
    }];
}
@end
```

```
import Nimble

class ObjcTest: XCTestCase {
    func testSwift() {
        waitUntil { (callback) in
            callback()
        }
    }
}
```

Works perfectly and getting references to swift side of this methods.

### PR DESCRIPTION
**Pull request by ikesyo**
This enables us to use Swift internal classes from Objective-C side with importing the generated header.

Fixes #477.

### CODE REVIEW

**Comment by wongzigii** [comment]
Should we also turn on `APPLICATION_EXTENSION_API_ONLY` in Quick ?

**Comment by ikesyo** [comment]
Might be yes: https://github.com/Quick/Quick/issues/749

**Comment by wongzigii** [comment]
:shipit:

**Comment by afetrifork** [comment]
This is causing a warning in my project: 
image

Any fixes for that?

**Comment by axandreo** [comment]
I am getting the same warning as @afetrifork . Additionally, I can't tell if they're related but, I started getting this issue 

```
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `Nimble` required by `Podfile`
- `Nimble` required by `Podfile`
- `Nimble (= 7.1.2)` required by `Podfile.lock`

None of your spec sources contain a spec satisfying the dependencies: `Nimble, Nimble (= 7.1.2)`.
```
The error instructs me to do `pod repo update`. However,  invoking `pod repo update` doesn't solve this error.

**Pull request merged**
