### PR TITLE
Fix README code example on Custom Validation

### PR DESCRIPTION
**Pull request by leefilll**
The PR should summarize what was changed and why. Here are some questions to
help you if you're not sure:

- Updates readme with working sample code.
- The codes in document currently is not working as well

Checklist - While not every PR needs it, new features should consider this list:

- [ ] Does this have tests?
- [x] Does this have documentation?
- [ ] Does this break the public API (Requires major version bump)?
- [ ] Is this a new feature (Requires minor version bump)?

### CODE REVIEW

**Comment by younata** [comment]
Hey @leefilll! We appreciate your contribution!

Fortunately, the existing documentation is correct. The `succeed` matcher does not exact a closure returning `ToSucceedResult`. You can verify this with the [ToSucceedTest.swift](https://github.com/Quick/Nimble/blob/main/Tests/NimbleTests/Matchers/ToSucceedTest.swift) which passes and demonstrates how to use the `succeed` matcher.

I'm going to close this, but we welcome future contributions you may have.

**Comment by leefilll** [comment]
Thank you for your kind reply @younata !!
I understood what you said.
 However, if you write the code according to the current document, it still throws a compilation error as follows.

image

I think, if you write the code as described in the document, it is not possible to infer the return type of the closure in Xcode, so a compilation error occurs. Because when we write code without any explicit type to disambiguate in closure, Xcode use [this](https://github.com/Quick/Nimble/blob/e313d9a67ec2e4171d416c61282e49fc3aadc7a4/Sources/Nimble/DSL.swift#L20) method instead of [this](https://github.com/Quick/Nimble/blob/e313d9a67ec2e4171d416c61282e49fc3aadc7a4/Sources/Nimble/DSL.swift#L2).

So I think it should be expressed in one of the following ways in the document.

- **Add explicit type to disambiguate**
```diff
-  expect {
+  expect { () -> ToSucceedResult in
    guard case .enumCaseWithAssociatedValueThatIDontCareAbout = actual else {
      return .failed(reason: "wrong enum case")
    }
    return .succeeded
  }.to(succeed())
```

- **Add another nested brace**
```diff
-  expect {
+  expect {{
    guard case .enumCaseWithAssociatedValueThatIDontCareAbout = actual else {
      return .failed(reason: "wrong enum case")
    }
    return .succeeded
-  }.to(succeed())
+  }}.to(succeed())
```
or
```diff
  expect {
    guard case .enumCaseWithAssociatedValueThatIDontCareAbout = actual else {
-      return .failed(reason: "wrong enum case")
+      return { .failed(reason: "wrong enum case") }
    }
-    return .succeeded
+    return { .succeeded }
  }.to(succeed())
```

If there's anything I missed, I'd appreciate it if you could tell me

**Comment by younata** [comment]
Perhaps I'm setting this up incorrectly, but I don't have this issue with the current shipping xcode (13.4), nor the current beta for xcode 14 (beta 4). I didn't try earlier versions of xcode.

Using XCTest:

Screenshot depicting [using the nimble custom validation documentation code with xctest, showing successful compilation, a correctly-passing assertion and a correctly-failing assertion](https://user-images.githubusercontent.com/285321/183129049-a0c362b0-42bc-4f17-81c8-2fef801b0d3c.png)

Using Quick:

Screenshot depicting [using the nimble custom validation documentation code with Quick, showing successful compilation, a correctly-passing assertion and a correctly-failing assertion](https://user-images.githubusercontent.com/285321/183129760-8bba5ec8-cc41-434d-8398-473dcc715c51.png)

To be clear, I believe that you're actually seeing this. I just don't understand how you're seeing it.

**Comment by leefilll** [comment]
Thank you for reply @younata.
I found the reason. I was using the nimble 9.2.x version... I updated it to the latest version of 10.0.0, and it works fine.
It was my mistake... 🥲 Thank you for your answer.

**Pull request closed without merging**
