### PR TITLE
Add a matcher for testing ErrorType values

### PR DESCRIPTION
**Pull request by briancroom**
As [promised](https://twitter.com/aikoniv/status/703114528943316993), here is a matcher that assists with working with Swift errors. I've been finding myself needing this while testing promises, because they vend raw `ErrorType` values as opposed to a function that can throw.

While digging into the implementation I realized that the core logic for this already exists in the `throwError` matcher, so I moved a bunch of that code into a separate file and used it to make the new matcher pretty trivial.

I'm not 100% convinced that `matchError` is the correct name for this, but I preferred it over `equalError` because standard equatability isn't required on the type. Are there any other suggestions?

```swift
expect(error).to(matchError(Error.Laugh))
expect(error).to(matchError(Error.self))
expect(error).to(matchError(EquatableError.Parameterized(x: 1)))
```

### CODE REVIEW

**Comment by briancroom** [comment]
Any feedback on this? @Quick/contributors @rbobbins :grinning:

**Comment by modocache** [comment]
Oy, sorry for not reviewing this sooner. I think it looks great!!

I initially wondered about the naming of the `matchError()`, but I guess it's named that in order to differentiate it from `throwsError()`. I think it'd be a good idea to document what this matcher does in the "Swift Error Handling" portion of the README. A blurb on the difference between this and the `throwsError()` matcher would also be nice.

@jeffh, do you have any thoughts here? I plan on merging this soon, unless you have any additional feedback.

**Comment by briancroom** [comment]
Thanks for one again encouraging me to produce documentation for my work @modocache! I've added the new matcher to the README now.

**Comment by jeffh** [comment]
LGTM, Thanks @briancroom!

**Comment by ysyyork** [comment]
Is error really compared using the implementation of equatable?

I implement my error type to conform Equatable but the == function never called when I run the test. And I dig into the source code and find in Errors.swift there are such lines of code from line 65 to 69:
`
if let error = error {
            if !errorMatchesExpectedError(actualError, expectedError: error) {
                matches = false
            }
        }
`
Then I try to see what is the logic inside the errorMatchesExpectedError function but saw there are two same function from line 37 to 53:
`
internal func errorMatchesExpectedError<T: Error>(
    _ actualError: Error,
    expectedError: T) -> Bool {
    return actualError._domain == expectedError._domain
        && actualError._code   == expectedError._code
}

internal func errorMatchesExpectedError<T: Error>(
    _ actualError: Error,
    expectedError: T) -> Bool
    where T: Equatable
{
    if let actualError = actualError as? T {
        return actualError == expectedError
    }
    return false
}
`

And every time it runs the first one which is compare error domain and code.

**Pull request merged**
