### PR TITLE
fix deployment target

### PR DESCRIPTION
**Pull request by oks**

### CODE REVIEW

**Comment by jeffh** [comment]
Hey @oks,

Thanks for the pull request. Although Nimble has these warnings, they're purposefully there because it does run on for iOS 7 (see [PR](https://github.com/Quick/Nimble/pull/102)). I don't know how common it is to still support iOS 7 targets, but in the past we've received PRs reverting these changes. Perhaps @modocache may know?

**Comment by oks** [comment]
Okay, but maybe we can shut this warning, somehow?

**Comment by jeffh** [comment]
If you can submit a PR to suppress this warning, that would be great!

**Comment by jeffh** [comment]
Hey @oks,

Please submit another PR if you figure out how to suppress this warning :smile:. I'll be closing this one, thanks for submitting a PR.

**Pull request closed without merging**
